name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag rohith/docker-react:$(date +%s)
    - name: Run tests step
      run: docker run rohith/docker-react npm run test
